apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: exemple-voting-app-template
objects:
- apiVersion: v1
  data:
    database-name: db
    database-password: postgres
    database-user: postgres
  kind: Secret
  metadata:
    name: db
    
- apiVersion: v1
  data:
    database-password: redis_password
  kind: Secret
  metadata:
    name: redis

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: result
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'result:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /result
    git:
      ref: master
      uri: 'https://github.com/mmumshad/example-voting-app.git'
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: PORT
          value: '8080'
      from:
        kind: ImageStreamTag
        name: 'nodejs:10'
        namespace: openshift
    type: Source
  triggers:
    - generic:
        secret: adcbfd88111b0798
      type: Generic
    - github:
        secret: fe2f6151edbbe108
      type: GitHub
    - imageChange:
        lastTriggeredImageID: >-
          172.30.1.1:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e
      type: ImageChange
    - type: ConfigChange
status:
  lastVersion: 1

-   


